language: generic
sudo: required
services:
  - docker

  before_install:
    - docker build -t ognjen02/frontend -f Dockerfile.dev .

  script:
    - docker run -e CI=true ognjen02/frontend npm run test